name: Build
on:
  workflow_call:
    inputs:
      IMAGE_NAME: { required: true, type: string }

    secrets:
      DOTENV: { required: true }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_REPOSITORY_OWNER --password-stdin

      - name: DOTENV
        run: |
          echo "${{ secrets.DOTENV }}" >> .env
          echo IMAGE_NAME="${{ inputs.IMAGE_NAME }}" >> .env

      - name: Build Docker images
        run: docker compose build

      - name: Push to GitHub registry
        run: docker push ${{ inputs.IMAGE_NAME }}
